version: '3'
services:
  nginx: 
    image: nginx:latest
    container_name: nginx_rev
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/error.log:/etc/nginx/error_log.log
      - ./nginx/cache/:/etc/nginx/cache
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443

  ctfd:
    image: ctfd/ctfd:latest
    container_name: isag_ctfd
    expose:
      - "8080:8080"

  grafana:
    image: grafana/grafana:latest
    container_name: monitor_grafana
    expose:
      - "3000:9999"
    environment:
      GF_SERVER_ROOT_URL: monitor.ctf.kmi.tl
